# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20170810_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together=set([('post', 'user')]),
        ),
    ]
