# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170813_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together=set([]),
        ),
    ]
